#define WIN32_LEAN_AND_MEAN // Stop the compiler from using "extra" definitions from windows.h which already includes some version of winsock

#include "gtest/gtest.h"
#include <iostream>
#include <fstream>
#include <vector>
#include <Windows.h>
#include <WinSock2.h>
#include <WS2tcpip.h>

#include "../3DServer/SocketHelper.h"
#include "../3DServer/Grafica.h"

// To add new class for unit testing:
// Go Project->Properties->Linker->Input->Additional Dependencies
//		and add the '.obj' file generated by the respective cpp
// DO NOT addd the Source.obj file as it contains a definition of 'main' which will create conflicts

// Dummy declaration - just for the sake of compilation
bool parser(CLIENT_STRUCTURE& client) {
	return 0;
}

TEST(TestOpenGLClass, TestInit) {
	Grafica obj;
	EXPECT_FALSE(obj.isInitialized());
}

TEST(TestOpenGLClass, TestSetSize) {
	Grafica obj;
	int dim = 0;

	obj.setSize(100, 100);
	dim = 100 * 100;
	EXPECT_EQ(obj.getBufferSize()/4,dim);

	obj.setSize(210, 300);
	dim = 210 * 300;
	EXPECT_EQ(obj.getBufferSize() / 4, dim);

	obj.setSize(320, 480);
	dim = 320 * 480;
	EXPECT_EQ(obj.getBufferSize() / 4, dim);
}

TEST(TestSocketClass, TestValidClient) {
	CLIENT_STRUCTURE temp;
	temp.talksHTTP = true;
	EXPECT_EQ(isClientValid(temp), true);

	temp.talksHTTP = false;
	EXPECT_EQ(isClientValid(temp), false);
}