name: MSBuild

## Haha...the suggested and default environment ${{env.GITHUB_WORKSPACE}} is not defined and gives error despite the documentation talking and using this variable
## It seems the correct one should be ${{ github.workspace }}...why should you bother github?
## https://github.community/t/github-workspace-variable-empty/137517/3

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  PROJECT_ROOT: ${{ github.workspace }}
  OUTPUT_PATH: ${{ github.workspace }}\Output
  SOLUTION_FILE_PATH: ${{ github.workspace }}\Server\3DServer
  RELEASE_FILE_PATH: ${{ github.workspace }}\Server\3DServer\Release
  TESTS_FILE_PATH: ${{ github.workspace }}\Server\3DServer\CodeTests
  
  CLIENT_SOLUTION_FILE_PATH: ${{ github.workspace }}\Client\scene-renderer
  WEBSITE_ROOT_FILE_PATH: ${{ github.workspace }}\Client\www
  WEBSITE_SCRIPTS_FILE_PATH: ${{ github.workspace }}\Client\www\assets\js
  
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release #Compile and Test on release version
  BUILD_PLATFORM: x86
  
jobs:
 

  publish:
    runs-on: windows-latest
    if: success() && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    - name: Echo environment
      run: |
        echo ${{ github.workspace }} 
        echo ${{env.SOLUTION_FILE_PATH}}\${{env.BUILD_CONFIGURATION}}\3DServer.exe
        
    - name: Download server artifact
      uses: actions/download-artifact@v2
      with:
        name: server-artifact

    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Install dependencies    
      working-directory: ${{ env.CLIENT_SOLUTION_FILE_PATH }}
      run: npm install

    - name: Build project
      working-directory:  ${{ env.CLIENT_SOLUTION_FILE_PATH }}
      run: npm run build

    - name: Publishing client library
      working-directory: ${{ env.CLIENT_SOLUTION_FILE_PATH }}
      run: |
          git config user.name 'AntonVonDelta'
          git config user.email '25268629+AntonVonDelta@users.noreply.github.com'
          git add index.js
          git commit -am "Automated build of client library"
          git push --force
          
    - name: Constructing output folder
      working-directory: ${{ env.CLIENT_SOLUTION_FILE_PATH }}
      run: |
          mkdir ${{ env.WEBSITE_SCRIPTS_FILE_PATH }}
          mkdir ${{ env.OUTPUT_PATH }}
          copy index.js ${{ env.WEBSITE_SCRIPTS_FILE_PATH }}/index.js
          xcopy "${{ env.WEBSITE_ROOT_FILE_PATH }}\" "${{ env.OUTPUT_PATH }}\"
          xcopy "${{env.RELEASE_FILE_PATH}}\" "${{ env.OUTPUT_PATH }}\"
          
    - name: Archive project
      uses: papeloto/action-zip@v1
      with:
        files: ${{ env.OUTPUT_PATH }}
        recursive: true
        dest: latest.zip
