# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ${{ github.workspace }}/Client/scene-renderer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
        
    - name: Install dependencies    
      working-directory: ${{ env.SOLUTION_FILE_PATH }}
      run: npm install
      
    - name: Build project
      working-directory:  ${{ env.SOLUTION_FILE_PATH }}
      run: npm run build
      
    - name: Running tests 
      working-directory: ${{ env.SOLUTION_FILE_PATH }}
      run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      
      - name: Publishing results
        working-directory: ${{ env.SOLUTION_FILE_PATH }}
        run: |
            ls
            git config user.name 'AntonVonDelta'
            git config user.email '25268629+AntonVonDelta@users.noreply.github.com'
            git add index.js
            git commit -am "Automated build of client library" || true
            git push --force
