# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ${{ github.workspace }}/Client/scene-renderer
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies    
      working-directory: ${{ github.workspace }}
      run: npm install ${{ env.SOLUTION_FILE_PATH }}
      
    - name: Build project
      working-directory: ${{ github.workspace }}
      run: npm run build ${{ env.SOLUTION_FILE_PATH }}
      
    - name: Compile TypeScript
      working-directory: ${{ github.workspace }}
      run: npm run lint ${{ env.SOLUTION_FILE_PATH }}
      
    - name: Running tests 
      working-directory: ${{ github.workspace }}
      run: npm test ${{ env.SOLUTION_FILE_PATH }}
